apiVersion: v1
items:
- apiVersion: autoscaling/v1
  kind: HorizontalPodAutoscaler
  metadata:
    name: invoker-scaler
    namespace: openwhisk
  spec:
    maxReplicas: 6
    minReplicas: 4
    scaleTargetRef:
      apiVersion: extensions/v1beta1
      kind: Deployment
      name: invoker
    targetCPUUtilizationPercentage: 60
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
